network_params:
  kernel_widths: [20, 0, 20, 20, 0, 6, 0, 6]  
  filters: [32, 0, 32, 32, 0, 32, 0, 32]  
  dropouts: [0.4, 0.4] 
  layer_types: ['C', 'N', 'C', 'C', 'P','C', 'N', 'C', 'P', 'flatten', 'F', 'D','F', 'D', 'F', 32, 16, 2] 
  name: "Modelo1"
