# """
# Configuration parameters for defining neural network models.

# Each configuration consists of the following parameters:

# kernel_widths (list): List of integers specifying the width of the convolutional kernels for each convolutional layer.

# filters (list): List of integers specifying the number of filters for each convolutional layer.

# dropouts (list): List of floats specifying the dropout rates for each dropout layer.

# layer_types (list):List specifying the types of layers to be included in the network.
# Each element represents a layer and can be one of the following:
#   - 'C': Convolutional layer
#   - 'N': Normalization layer
#   - 'P': Pooling layer
#   - 'flatten': Flatten layer
#   - 'F': Dense layer
#   - 'D': Dropout layer
#   - Integers: Representing the number of neurons in the dense layers.

# name (str): Name of the model.
# """
configurations:
  config1:
    kernel_widths: [20, 20, 6, 6, 6]
    filters: [32, 32, 32, 32, 32]
    dropouts: [0.4, 0.4, 0.4]
    layer_types: ['C', 'C', 'N', 'C', 'C', 'C', 'N', 'P', 'flatten', 'F', 'D', 'F', 'D', 'F', 'D', 'F', 256, 128, 32, 2]
    name: "Modelo1"

  config2:
    kernel_widths: [10, 10, 8, 8, 8]
    filters: [16, 16, 16, 16, 16]
    dropouts: [0.3, 0.3, 0.3]
    layer_types: ['C', 'C', 'N', 'C', 'C', 'C', 'N', 'P', 'flatten', 'F', 'D', 'F', 'D', 'F', 'D', 'F', 128, 64, 16, 2]
    name: "Modelo2"
    
  # config3:
  #   kernel_widths: [20, 0, 20, 20, 0, 6, 0, 6]  
  #   filters: [32, 0, 32, 32, 0, 32, 0, 32]  
  #   dropouts: [0.4, 0.4] 
  #   layer_types: ['C', 'N', 'C', 'C', 'P','C', 'N', 'C', 'P', 'flatten', 'F', 'D','F', 'D', 'F', 32, 16, 2] 
  #   name: "Modelo3"

